### ISSUE TITLE
Errors on search & failing /ngrams?query=trump

### ISSUE THREAD

**Issue by RuiluGao** [mikeizbicki/cmc-csci143#197] opened 2022-04-28 21:21 UTC
Hi Mike,

After I have built the docker and did the port forwarding, the starting page works fine, but for any search and I ran into this error:
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "metahtml_rollup_langmonth" does not exist
LINE 14:         from metahtml_rollup_langmonth
                      ^

[SQL: 
    select  
        extract(epoch from x.time ) as x,
        
        coalesce(y0/total.total,0) as y0
        
    from (
        select generate_series('2000-01-01', '2020-12-31', '1 month'::interval) as time
    ) as x
    left outer join (
        select
            hostpath as total,
            timestamp_published as time
        from metahtml_rollup_langmonth
        where 
                language = 'en'
            and timestamp_published >= '2000-01-01 00:00:00' 
            and timestamp_published <= '2020-12-31 23:59:59'
    ) total on total.time=x.time
    
    left outer join (
        select
            hostpath as y0,
            timestamp_published as time
        from metahtml_rollup_textlangmonth
        where 
            alltext = %(term0)s
            and language = 'en'
            and timestamp_published >= '2000-01-01 00:00:00' 
            and timestamp_published <= '2020-12-31 23:59:59'
    ) y0 on x.time=y0.time
    
    order by x asc;
    ]
[parameters: {'term0': 'google'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
```
I'm not sure where exactly is causing it and how should I go about fixing it?

I've also changed the port for `scripts/check_web_endpoints.sh` and when I ran
```
$ sh scripts/check_web_endpoints.sh
```
I had two tests passing with one failed:
```
[pass]    / 
[pass]    /ngrams 
[fail]    /ngrams?query=trump 
```
I suspect that might be the same issue causing the errors in my web search. Any suggestion on going about fixing them?

**Comment by mikeizbicki** [comment] 2022-04-29 16:46
The error message
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "metahtml_rollup_langmonth" does not exist
```
makes me think that you don't have any tables in your database.  You can verify this by running `\d` in psql.  This would be caused by postgres crashing partway through your initialization process, which I would guess was also the problem you fixed in #191.

You will have to run the `schema.sql` file in order to build the database tables.  You can do this by resetting everything and starting from scratch (slow, but maybe more straightforward) or manually passing this file into psql (you'll have to come up with a good command combining docker-compose and input redirection, but it'll be really fast).

**Comment by RuiluGao** [comment] 2022-04-30 04:53
Yes, I did verify there are no tables in my database. I'm a bit confused about starting from scratch though. I tried to rebuild the container and it wouldn't work. What exactly should I reset from scratch?

**Comment by mikeizbicki** [comment] 2022-04-30 22:21
You would need to delete the database (inside the volume) and have it be recreated.

**Comment by RuiluGao** [comment] 2022-05-04 22:22
Here is the solution that I have discussed with Mike for people who are facing the same issue:

```
$ docker-compose exec -T pg psql --user=novicheinko < services/pg/sql/schema.sql
```
However, in order to have this line work, we need to first solve the submodule issue with one particular folder `services/pg/data` by running:
```
$ git submodule init
$ git submodule update
```
so that we pulled the submodules linked in the folder.

And the docker-compose code should work fine then.

**Closed as completed** 2022-05-12 19:08 UTC
Labels: question
