### ISSUE TITLE
Error with pg_normalized_batch

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci143#162] opened 2022-04-11 19:16 UTC
pg_denormalized ran in 18:40.13, but this error occured when it tried to load pg_normalized_batch.  

Is the schema we have the updated one? 

```
psycopg2.errors.UndefinedTable: relation "urls" does not exist
LINE 2:     insert into urls
                        ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "load_tweets_batch.py", line 458, in <module>
    insert_tweets(connection,tweets,args.batch_size)
  File "load_tweets_batch.py", line 175, in insert_tweets
    _insert_tweets(connection, tweet_batch)
  File "load_tweets_batch.py", line 212, in _insert_tweets
    user_id_urls = get_id_urls(tweet['user']['url'])
  File "load_tweets_batch.py", line 55, in get_id_urls
    res = connection.execute(sql,{'url':url}).first()
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1295, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1497, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1852, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2033, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "urls" does not exist
LINE 2:     insert into urls
                        ^

[SQL:
    insert into urls
        (url)
        values
        (%(url)s)
    on conflict do nothing
    returning id_urls
    ;
    ]
[parameters: {'url': 'https://instagram.com/larissacarrionnails?igshid=1momcd02rgs5p'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
2022-04-11 11:22:13.587135 /data/tweets/geoTwitter21-01-08.zip
2022-04-11 11:22:38.710975 insert_tweets i= 0
Traceback (most recent call last):
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "urls" does not exist
LINE 2:     insert into urls
                        ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "load_tweets_batch.py", line 458, in <module>
    insert_tweets(connection,tweets,args.batch_size)
  File "load_tweets_batch.py", line 175, in insert_tweets
    _insert_tweets(connection, tweet_batch)
  File "load_tweets_batch.py", line 212, in _insert_tweets
    user_id_urls = get_id_urls(tweet['user']['url'])
  File "load_tweets_batch.py", line 55, in get_id_urls
    res = connection.execute(sql,{'url':url}).first()
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1295, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1497, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1852, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2033, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/Kieran.Daly.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "urls" does not exist
LINE 2:     insert into urls
                        ^

[SQL:
    insert into urls
        (url)
        values
        (%(url)s)
    on conflict do nothing
    returning id_urls
    ;
    ]
[parameters: {'url': 'https://www.twitter.com/city_pantry'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
Command exited with non-zero status 10
247.91user 31.24system 0:33.30elapsed 838%CPU (0avgtext+0avgdata 3022288maxresident)k
440inputs+4128outputs (6major+16165840minor)pagefaults 0swaps
```

**Comment by mikeizbicki** [comment] 2022-04-11 20:19
Closing as a duplicate of #161.

**Closed as completed by mikeizbicki** 2022-04-11 20:19 UTC
