### ISSUE TITLE
Error when trying to build docker container

### ISSUE THREAD

**Issue by axelahdritz** [mikeizbicki/cmc-csci143#172] opened 2022-04-19 02:32 UTC
Hey Mike!

I am having trouble running docker commands on my user account on the lambda server. When I try to run `docker ps`, I am getting this error:

```
Cannot connect to the Docker daemon at unix:///run/user/1149/docker.sock. Is the docker daemon running?
```
The solutions online all required admin privileges and restarting docker, so I am a little stumped. I believe whatever problem is occurring above is what is causing everything to crash when I attempt to run `docker-compose up -d --build`. See this beast of an error below:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Axel.Ahdritz.22/.local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/compose/cli/command.py", line 70, in project_from_options
    enabled_profiles=get_profiles_from_options(options, environment)
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/compose/cli/command.py", line 153, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/compose/cli/docker_client.py", line 43, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/Axel.Ahdritz.22/.local/lib/python3.6/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
    f'Error while fetching server API version: {e}'
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

Any help on this error would be great, and I might be missing something obvious :/

All the best,
Axel

**Comment by mikeizbicki** [comment] 2022-04-19 04:05
You need to restart the docker daemon.  See the commands that start with `systemctl` at this link: <https://docs.docker.com/engine/security/rootless/#troubleshooting>.

Also, we are using "rootless docker", and so that is the key phrase that you need to google in order to get the right results that don't require root access.

**Comment by axelahdritz** [comment] 2022-04-20 02:31
Hey Mike!

So I cannot restart docker using the `systemctl --user start docker` command. I get the error:

```
Failed to connect to bus: No such file or directory
```

Thinking that something must have gotten garbled somewhere, I thought I would try to uninstall rootless docker and then reinstall everything. However, when I attempt to uninstall the dockerd-rootless-setuptool.sh I get the following error:
```
[INFO] systemd not detected, dockerd-rootless.sh needs to be stopped manually:
[INFO] This uninstallation tool does NOT remove Docker binaries and data.
[INFO] To remove data, run: `/home/Axel.Ahdritz.22/.local/bin/rootlesskit rm -rf /home/Axel.Ahdritz.22/.local/share/docker`
```
And I get a similar error when I attempt to install it:
```
[INFO] systemd not detected, dockerd-rootless.sh needs to be started manually:

PATH=/home/Axel.Ahdritz.22/.local/bin:/sbin:/usr/sbin:$PATH dockerd-rootless.sh 

[INFO] CLI context "rootless" already exists

[INFO] Make sure the following environment variables are set (or add them to ~/.bashrc):

export PATH=/home/Axel.Ahdritz.22/.local/bin:$PATH
export DOCKER_HOST=unix:///run/user/1149/docker.sock

```
What does this mean?

All the best,
Axel

**Comment by mikeizbicki** [comment] 2022-04-20 03:48
I believe this problem should be fixed now.

The root of the problem is that your systemd instance was killed when I killed all of your other processes that were exhausting the lambda server's resources.  So I restarted your systemd process for you, and verified that `docker ps` does in fact work now.

Because this problem was caused by my and not you, you can have a 48 hour extension on the assignment to make up for the inconvenience.

**Comment by axelahdritz** [comment] 2022-04-20 04:00
Thank you so much! I had a suspicion it was because of the Capstone work...

**Comment by axelahdritz** [comment] 2022-04-22 05:01
Hey Mike!

Things were working again for a moment, until they werent! I apologize for once again opening this issue. I ran a `killall` command after running a script that was on its way to create a memory error, and found that my rootless docker container was once more stopped. When I ran the `systemctl --user start docker` command however, I got the same error as before:
```
Failed to connect to bus: No such file or directory
```
And when I tried to install the docker rootless bash script again,  I got this error:
```
[INFO] systemd not detected, dockerd-rootless.sh needs to be stopped manually:
[INFO] This uninstallation tool does NOT remove Docker binaries and data.
[INFO] To remove data, run: `/home/Axel.Ahdritz.22/.local/bin/rootlesskit rm -rf /home/Axel.Ahdritz.22/.local/share/docker`
```
As such, I realized that the `systemd` instance was killed. This was my mistake this time! Is there any way to start the systemd instance on my end without turning off the lambda server and rebooting it?

I apologize for the inconvenience of all of this...

All the best,
Axel

**Comment by mikeizbicki** [comment] 2022-04-22 18:06
It is technically possible to restart a user level systemd instance without restarting the computer, but I've never been able to figure out the incantation to do it on the lambda server.  Anyways, I've restarted the server so the issue should be fixed.

**Closed as completed** 2022-04-25 14:28 UTC
Labels: question
