### ISSUE TITLE
Required reading / viewing

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#45] opened 2021-03-16 23:41 UTC
Recall that in order to earn a grade that is at least an A- in this class, you must either read a section of The Art of Unix Programming or watch two documentaries. (Details and links are in the syllabus.) In order to get credit for having completed this assignment, you should reply to this post with a 2-3 sentence description of your favorite part of the reading/viewing.

**Comment by saatvik7** [comment] 2021-03-17 17:44
Hello! I watched the two documentaries over Spring Break and I especially enjoyed watching Revolution OS. I was really impressed by the work done by Richard Stallman on the GNU project and by Linus Torvalds on Linux, and how we're still using these Operating Systems that were developed over two decades ago. I also learned that Firefox was originally called the Netscape Browser. I was also very inspired by the documentary on Aaron Swartz, who invented RSS, co-founded Reddit, and led so many civic awareness campaigns. It was truly very tragic how he ended his life and I can only wonder what else he would have gifted to the internet if he was still alive.

**Comment by nguyenank** [comment] 2021-03-23 19:05
I read the first section (the first three chapters) of The Art of Unix Programming. My favorite part was the repetitive mention of pipes and their fundamental importance to all components of Unix described in the section: Unix's philosophy, history, and particular style of operating system; I knew very few of the terms tossed around in the section (especially in the history section - I'm still not entirely sure of the difference between minicomputers, mainframes, workstations, and PCs, even if I grasped the economic implications of their market niches on Unix's history), but pipes are something I understand and could use to ground myself in the reading. In particular, the prevalence of pipes throughout the section made the discussion of Unix's philosophy, which otherwise seemed a bit vague and obvious, more concrete, as many rules stated like of Modularity and Transparency and Simplicity are immediately obvious through pipes. It also made the quick transition from originally 10 or so to 17 rules because of "implied" principles hilarious rather than a stretch, because I believed at that point in the existence of a unifying theory of Unix development, all because of pipes.

**Comment by samuellee19** [comment] 2021-04-07 04:18
After watching the two documentaries, I realized how we are able to enjoy a vast array of software libraries and packages due to voices made by software activists, such as Richard Stallman and Aaron Swartz. If nobody fought against having access to source codes (against AT&T or Microsoft), modern computers and the internet would have been severely restricted, bounded by corporates' interests. As Linux functions (e.g., grep) that we extensively use in this course exist thanks to the efforts of numerous open-source engineers, I realized that I should respect and contribute to GNU or any other open-source licenses and communities (same goes to Creative Commons!) In fact, it is very amazing to see how many different Linux distros are available for free (all with different setups for different purposes) as a result of the above movements.

Also, check out this youtube channel, Fireship! Very relevant and entertaining:
- [Why so many distros? The Weird History of Linux](https://www.youtube.com/watch?v=ShcR4Zfc6Dw)
- [7 Database Paradigms](https://www.youtube.com/watch?v=W2Z7fbCLSTw)

**Comment by amytam01** [comment] 2021-04-07 05:07
I decided to read chapters 1-3 of The Art of Unix Programming. Reading about Unix was overall really satisfying and helped me appreciate the system all the more as a result of better understanding it's art, philosophy, and pros/cons (though I am not a personal fan of the system). I also really enjoyed how the chapters were written (there's a lot of personality incorporated). My favorite part of the reading was Chapter 1, about Unix's philosophy. It reminds me a lot of good programming practices, but more specifically building great unit tests (for example, modularity, clarity, simplicity, robustness, optimization, etc). My second favorite part would be Chapter 2, reading the origin story of Unix with such humble and heartwarming beginnings baffles me, as Unix is such an integral foundation of the operating systems of today (I would definitely watch a movie on this).

**Comment by anan-ara** [comment] 2021-04-14 16:19
I watched the two documentaries, Revolutionary OS and The Internet's Own Boy: The Story Of Aaron Swartz. My favorite part of Revolutionary OS was the part where Richard Stallman explained the philosophy behind the free software movement and what the "free" in free software really means. It changed the way I view free software and how software should be developed and distributed in general. My favorite part of The Internet's Own Boy: The Story Of Aaron Swartz is the part at the very end where they talked about a young boy who reached out to Johns Hopkins researchers about pancreatic cancer and how they managed to make a test for it. This would not have been possible without the efforts of Aaron Schwarz towards free knowledge and I think ending the documentary with that shows the importance of what Aaron Schwarz was fighting for.

**Comment by cduong21** [comment] 2021-04-19 18:15
I enjoyed watching both the documentaries. In Revolution OS, Moore was able to capture the essential idea behind open-source programs and operating systems. As a programmer, I've reaped the benefits of many different open source libraries. To think that at the beginning of modern-day programming, all things were proprietary is interesting since the engineering culture I have been exposed to has always been a huge proponent for collaboration and discourse. I agree with the philosophy set forth about the importance of free software and am glad that it's widely understood (at least I hope) in the engineering field now! It's a great way to continue iterating and improving software. The Internet’s Own Boy was a moving documentary and a historically important piece to the creation of the internet. Aaron’s political activism in tandem with his programming abilities paved the way for lots of legislative reform in a novel space. I’m sure with everything going on in the recent years in specific to dealing with anti-trust legislation, Aaron Swartz would have had a great pool of knowledge and insights for the world.

**Comment by afzal-p** [comment] 2021-05-05 18:32
RevolutionOS had a great story arc by first introducing the pessimistic letter from Bill Gates and then concluding with the successful public offering. My favorite part was the organization that had occurred during the protest agains microsoft's terms of use with windows being pre-installed on computers. Neither manufacturers nor microsoft were willing to budge on refunding the windows os, shining a light on their greed and monopolistic beliefs. The creation of linux proves it is possible for open source projects to have wide spread impact and be able to compete with industry standards. I was unaware of Aaron Swartz, so his story went from inspirational to tragic very fast. Perhaps if I was older his name would be familiar as he grew up just twenty minutes from where I currently live. My favorite part was seeing Aaron giving a talk to adults about his work with creative commons at a very young age. The internet's own boy also revealed interesting behaviors of lawyers and both campus and law enforcement. By planting cameras, law enforcement wanted to build a case depicting exaggerated cyber crime rather than determine what actually was happening. I was also confused with MIT showing Swartz little support by remaining a neutral party, and I'm sure their influence could have changed the trajectory of the prosecution.

**Comment by hwing777** [comment] 2021-05-05 23:12
I watched the two documentaries, Revolution OS and The Internet’s Own Boy. For both documentaries, I was really interested in the legal and political aspects of the stories told in each. For Revolution OS, it was interesting to see how explicitly Linux’s creation went against Microsoft’s dominance. Previously, I don’t think I fully grasped the importance of open source. I was still a child when many of the anti-trust lawsuits were filed against Microsoft, and by now it seems that Microsoft has tried very hard to change (or cover up) its image. I didn’t really grasp how much control these large tech companies held, and so I didn’t understand that open source truly was revolutionary. Similarly, learning about Aaron Swartz’s impact on free and open access to information made me reflect on how much I’ve taken for granted. From the existence of free information to the easy availability of open source projects, these things have transformed the way people work with and on software. Understanding their history has stopped me from taking these things for granted.

**Comment by lsanders99** [comment] 2021-05-07 17:47
I watched the documentaries RevolutionOS and The Internet's Own Boy. I found both really interesting, so I don't have a favorite part of in the actual movies. My favorite part of the viewing in general was the theme. It's helpful to remember the importance of open/free information, whether that be in terms of source code or written articles. It emphasizes projects such as the search engine project we did that provides information that we may rarely see/have access to. The first movie also emphasized that the internet was not always the place of open/free information that some of us may take for granted as people who grew up after the open source movement (like me). However, the second reminds us that it still isn't perfect and we still have a long way to go to have that "all information at our fingertips" ideal.

**Comment by ejarquin22** [comment] 2021-05-08 01:37
I read chapters 1-3 of The Art of Unix Programming. Unix's open-source community was particularly interesting to learn about because of how the community itself formed and working together long before the term "open-source" was even invented/defined, and even then the community has stuck together and continued since its start. I also found it really funny that all the philosophical principles behind Unix can be boiled down to a single idea, which is to K.I.S.S. (Keep it simple, stupid).

**Comment by Asanchez2112** [comment] 2021-05-08 04:33
For the required viewing/reading, I watched the documentaries RevolutionOS and The Internet's Own Boy. I found both documentaries to be extremely interesting in their topics. I found the overall development of Linux and GNU in RevolutionOS to be extremely interesting, especially in how they were leveraged as a way to further advance open-source software. I feel like this was an extremely important piece of history that has allowed for the use of open-source software today and the prevention of monopolies in the tech industry. In addition, I found the overall development of open-source software extremely fascinating in how it was defined to prevent monopolies or the privatization of software and how copyrights were issued. I also found it extremely interesting how even with these infringements, investors were still interested and saw the potential of open-source software. In The Internet's Own Boy, I found the development of access to free information and the impact of Aaron Swartz to be revolutionary. I feel that I take access to information for granted since it has always been available to me and was much smaller when a lot of these cases occurred. I also thought Aaron's overall accomplishments were extraordinary and I was completely unaware of his existence in history!

**Comment by chenpatrickc** [comment] 2021-05-09 07:29
I watched the documentaries RevolutionOS and The Internet's Own Boy. A part that I found to be comical in the RevolutionOS documentary was the apparent single sided power struggle between GNU and Linux, and how the GNU creator wanted to emphasize the name GNU/Linux while the Linux creator kind of just brushed it aside and didn't really care. One scene that I felt visualized this is when at the Linux conference, Linus's children are running around in the background recking havoc while Richard Stallman urged the audience to use the term GNU/Linux. What surprised me about The Internet's Own Boy was realizing I had lived through the anti-SOPA era and experienced the protests first hand. As my younger self I remembered the blackout of the Reddit cite and numerous posts urging users to take action. Usually documentaries are about topics that are more displaced from personal experience, so watching it and understanding the background was a treat. Aaron and his work ethic and mindset is something that really inspired me as well.

**Comment by CurtisSalinger** [comment] 2021-05-13 19:35
For my additional material, I watched the documentaries. The part I found the most interesting was the commentary on institutional access to research papers and scholarly journals in The Internet's Own Boy. I never really considered that the paywalls to get into these databases are double paying online publishers for research material. And in particularly, the fact that much of this research was paid for by public funding or grants only to then be locked up and paywalled. Additionally the whole structure where individuals do all the research and then have to relinquish their copyright to the multi-billion dollar companies who churn incredible profit off of the gatekeeping.

**Comment by valenxie** [comment] 2021-05-13 20:17
I watched the documentaries, both told really interesting stoies that I never heard of. I was really attracted and inspired to Aaron's optimistic personality and his attitude towards living - that it's not enough to just take what's given and follow the things that society told you to do, instead everything is open to questioning or recantation. It's for sure that if we blindly follow the rules it's hard to notice anything wrong or even try to make things right. I feel many people chose to do programming because of the high income, while Aaron initiated projects that could change the world. Living in a country where internet censorship has been in place for a long time, it's hard for me to imagine how the internet can be used as a tool to make political changes, yet Aaron along with many American citizens accomplished that.

**Comment by asapirstein** [comment] 2021-05-14 04:23
I had watched the two documentaties at the begining of the semester, but for some reason are just getting around to writing this now. There were three things - many of which have been said before, that stood out to me. Firstly, with few exceptions, I expect that the programs that I am working with will be  open source, that if I want to change something or tweak, I will be able to do so. Watching the pioneers of open source - notable Stallman - detail how and why it got this way was quite interesting. I could not help but wonder what they would say about the darker corners of the internet, as they clearly have gotten further and further from the utopic ideals that were embodied in the open source comunity. The Internet's Own Boy - helped me realize how revolutionary sitting behind a computer can be. I think the most interesting thing to me was that this sort of revolution is harder to see, and indeed the gradual erosion of rights that Aaron was trying to prevent was much much harder to see. Lastly, I guess Microsoft has some good PR people - my perception of them was as a giant that wrote a mediocre group of software pacakges that were user friendly but hard to modify - not as a group against open source software. This perception seems to be historically wrong.

**Comment by cschulz21** [comment] 2021-05-14 22:24
From the documentaries, I quite enjoyed the breakdown of the guidelines that constitute open-source and how that opens the code to others making improvements that also get released as open-source. I thought the marketing angle of the name creation was smart in avoiding using free as it can be associated with subpar. From The Internet's Own Boy, as with many others, I found the proportion that his crime was elevated to quite infuriating. I am happy to have learned about some of the major faults in data accessibility when it comes to public records and state funded research.

**Comment by whosayn** [comment] 2021-05-16 22:05
For my required viewing requirement, I watched the two documentaries. I was inspired to become a more active participant in the causes I care about because I can always contribute in some way. My favorite part of the Aaron Schwartz documentary was when he and his colleagues used an opportunity  at a library to implement a batch download of documents.  I was very surprised about how harshly he was treated, given his crime and about the college's unwillingness to step in. While I knew somewhat about paywalls behind accessing data online, I didn't know about how profitable the business was and what a monstrous institution is is. With the RevolutionOS documentary, I found it interesting to learn about how hard it is to develop open source software without infringing on any copyrights for any  of the included components. I never thought about code proprietorship as being  a thing.  While government interference  was a boon in this case, I still don't  know how I feel about that even though it helped to promote  the software as an alternative.

**Comment by mlaugharn** [comment] 2021-05-17 06:24
I watched the documentaries. I previously knew a bit about Aaron Swartz's story, but I didn't have such a firm understanding about how the prosecutors sought to make him an example. Nor did I realize that Heymann's prosecution of Swartz continued  even after JSTOR decided not to further pursue Swartz themselves. The most similar thing happening today is the prosecution of Alexandra Elbakyan, the founder of sci-hub, another tool for bypassing scholarly/journal paywalls - only a few weeks ago Elbakyan posted that the FBI were interested in surveilling her online activity as well. As for Revolution OS, it was quite interesting to see Bill Gates' original position against those who were against paying for software. The rest is history.. Linus made git, github was founded and is now essentially synonymous with open source software distribution, and its current owner is none other than Microsoft. Much of the software used to *build* software these days is open source. Free access but closed operations/data mining of online platforms - basically "free, but not open source" - is an interesting frankenstein successor to the idea of free software..

**Closed as completed** 2022-01-18 21:10 UTC
Labels: announcement
